plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
title: "Service de Consultation en IA et données"
description: "Service de consultation en intelligence artificielle et données de l'Institut Intelligence et données de l'université Laval. Réservé aux membres pour le moment."
show_downloads: false