plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
show_downloads: false

title: "Service de consultation en IA et données (SCIAD)"
description: "Service de consultation en intelligence artificielle et données de l'Institut intelligence et données de l'université Laval. Ce service est réservé aux chercheurs membres et collaborateurs de l'Institut (et leurs étudiant.e.s) pour le moment."
