plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-tactile
show_downloads: false

defaults: 
  - title: "Service de Consultation en IA et données"
  - description: "Service de consultation en intelligence artificielle et données de l'Institut Intelligence et Données de l'université Laval. Réservé aux membres pour le moment."
